/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Nicoll Pinzon
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roomHistory = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        newClient = new javax.swing.JButton();
        checkIn = new javax.swing.JButton();
        costumerRecord = new javax.swing.JButton();
        searchReservation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        roomHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Historial.png"))); // NOI18N
        getContentPane().add(roomHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 270, 110));

        checkOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-out.png"))); // NOI18N
        getContentPane().add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 280, 110));

        newClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Agregar2.2.png"))); // NOI18N
        getContentPane().add(newClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 280, 110));

        checkIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/check-in.png"))); // NOI18N
        getContentPane().add(checkIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, 110));

        costumerRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registro.png"))); // NOI18N
        getContentPane().add(costumerRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 270, 110));

        searchReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Busqueda.png"))); // NOI18N
        getContentPane().add(searchReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 270, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MENU.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkIn;
    private javax.swing.JButton checkOut;
    private javax.swing.JButton costumerRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newClient;
    private javax.swing.JButton roomHistory;
    private javax.swing.JButton searchReservation;
    // End of variables declaration//GEN-END:variables
}
